import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { BadgeDollarSign, FileCheck2, Landmark, RefreshCw } from "lucide-react";
import { AdminPanel } from "../../../components/admin/AdminPanel";
import { Button } from "../../../components/ui/button";
import { useAdminOutlet } from "../../../layouts/AdminLayout";
import { adminApi, formatCurrency, formatDate, type B2BContract, type B2BDebt, type B2BOverview } from "../../../lib/adminApi";
import { EmptyState, ErrorState, LoadingState } from "../shared/ApiState";
import { AdminPageShell } from "../shared/AdminPageShell";

export function B2BFinancePage() {
  const { token, sessionVersion } = useAdminOutlet(); const [data, setData] = useState<B2BOverview | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [contractId, setContractId] = useState(""); const [invoiceAmount, setInvoiceAmount] = useState(""); const [dueDate, setDueDate] = useState(""); const [paymentDebt, setPaymentDebt] = useState<B2BDebt | null>(null); const [paymentAmount, setPaymentAmount] = useState(""); const [transactionCode, setTransactionCode] = useState("");
  const load = useCallback(async () => { if (!token) return; setLoading(true); setError(""); try { setData(await adminApi.b2bOverview(token)); } catch (e) { setError(e instanceof Error ? e.message : "Không tải được dữ liệu B2B."); } finally { setLoading(false); } }, [token]);
  useEffect(() => { void load(); }, [load, sessionVersion]);
  const openDebts = useMemo(() => data?.debts.filter((item) => item.status !== "CLEARED") ?? [], [data]);
  async function updateContract(contract: B2BContract, status: B2BContract["status"]) { if (!token) return; try { await adminApi.updateB2BContract(token, contract.id, { status }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Không cập nhật được hợp đồng."); } }
  async function createInvoice(event: FormEvent) { event.preventDefault(); if (!token || !data) return; const contract = data.contracts.find((item) => item.id === Number(contractId)); if (!contract) { setError("Vui lòng chọn hợp đồng."); return; } try { await adminApi.createB2BInvoice(token, { contractId: contract.id, businessCustomerId: contract.businessCustomer.id, amount: Number(invoiceAmount), dueDate: dueDate || undefined }); setInvoiceAmount(""); setDueDate(""); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Không tạo được hóa đơn."); } }
  async function recordPayment(event: FormEvent) { event.preventDefault(); if (!token || !paymentDebt) return; try { await adminApi.recordDebtPayment(token, paymentDebt.id, { amount: Number(paymentAmount), transactionCode: transactionCode || undefined }); setPaymentDebt(null); setPaymentAmount(""); setTransactionCode(""); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Không ghi nhận được khoản thu."); } }
  return <AdminPageShell title="Hợp đồng, hóa đơn và công nợ" description="Theo dõi luồng B2B sau khi khách hàng chấp nhận báo giá.">
    {error ? <ErrorState message={error} /> : null}
    <div className="grid gap-4 md:grid-cols-3"><Metric icon={FileCheck2} label="Hợp đồng" value={data?.contracts.length ?? 0} /><Metric icon={Landmark} label="Hóa đơn" value={data?.invoices.length ?? 0} /><Metric icon={BadgeDollarSign} label="Công nợ còn mở" value={openDebts.length} /></div>
    <AdminPanel title="Lập hóa đơn từ hợp đồng" description="Hệ thống tự tạo một khoản công nợ để theo dõi thanh toán." action={<Button onClick={load} variant="outline" className="border-[#C7A792] text-[#553B2F]"><RefreshCw size={16} />Tải lại</Button>}><form onSubmit={createInvoice} className="grid gap-3 p-5 md:grid-cols-4"><select required value={contractId} onChange={(e) => setContractId(e.target.value)} className="h-10 rounded-lg border border-[#C7A792] px-3 text-sm font-semibold md:col-span-2"><option value="">Chọn hợp đồng</option>{data?.contracts.filter((x) => x.status !== "CANCELLED").map((x) => <option key={x.id} value={x.id}>{x.contractCode} - {x.businessCustomer.companyName}</option>)}</select><input required min={1} type="number" value={invoiceAmount} onChange={(e) => setInvoiceAmount(e.target.value)} placeholder="Giá trị hóa đơn" className="h-10 rounded-lg border border-[#C7A792] px-3 text-sm font-semibold" /><input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} className="h-10 rounded-lg border border-[#C7A792] px-3 text-sm font-semibold" /><Button className="bg-[#553B2F] text-white hover:bg-[#3f2a21] md:col-span-4">Tạo hóa đơn và công nợ</Button></form></AdminPanel>
    {loading ? <LoadingState /> : <div className="grid gap-5 xl:grid-cols-2"><AdminPanel title="Hợp đồng B2B" description="Tạo từ báo giá đã được chấp nhận.">{data?.contracts.length ? <div className="divide-y divide-[#E8D3C7]">{data.contracts.map((x) => <article key={x.id} className="flex flex-wrap items-start justify-between gap-3 p-5"><div><p className="font-black text-[#553B2F]">{x.contractCode} · {x.businessCustomer.companyName}</p><p className="mt-1 text-sm font-semibold text-[#7a5547]">{x.title}</p><p className="mt-2 text-xs font-bold text-[#AA7864]">{formatCurrency(x.totalValue)} · Đặt cọc {x.depositPercent}%</p></div><select value={x.status} onChange={(e) => void updateContract(x, e.target.value as B2BContract["status"])} className="h-9 rounded-lg border border-[#C7A792] bg-white px-2 text-xs font-bold text-[#553B2F]"><option value="DRAFT">Nháp</option><option value="ACTIVE">Đang hiệu lực</option><option value="COMPLETED">Hoàn thành</option><option value="CANCELLED">Hủy</option></select></article>)}</div> : <EmptyState message="Chưa có hợp đồng. Chuyển báo giá đã chấp nhận thành hợp đồng trước." />}</AdminPanel><AdminPanel title="Công nợ cần thu" description="Ghi nhận từng lần thu tiền, số dư cập nhật tự động.">{data?.debts.length ? <div className="divide-y divide-[#E8D3C7]">{data.debts.map((x) => <article key={x.id} className="flex flex-wrap items-start justify-between gap-3 p-5"><div><p className="font-black text-[#553B2F]">{x.debtCode} · {x.businessCustomer.companyName}</p><p className="mt-1 text-sm font-semibold text-[#7a5547]">Còn phải thu: {formatCurrency(x.remainingAmount)}</p><p className="mt-1 text-xs font-bold text-[#AA7864]">Hóa đơn {x.invoice?.invoiceCode ?? "Không liên kết"} · {x.dueDate ? `Hạn ${formatDate(x.dueDate)}` : "Chưa đặt hạn"}</p></div>{x.status !== "CLEARED" ? <Button onClick={() => { setPaymentDebt(x); setPaymentAmount(String(x.remainingAmount)); }} variant="outline" className="border-[#C7A792] text-[#553B2F] hover:bg-[#f8f2ed]">Thu tiền</Button> : <span className="text-sm font-black text-emerald-700">Đã tất toán</span>}</article>)}</div> : <EmptyState message="Chưa có công nợ B2B." />}</AdminPanel></div>}
    {paymentDebt ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={recordPayment} className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><h2 className="text-xl font-black text-[#553B2F]">Ghi nhận thu tiền</h2><p className="mt-2 text-sm text-[#7a5547]">{paymentDebt.debtCode} · còn {formatCurrency(paymentDebt.remainingAmount)}</p><input required min={1} max={paymentDebt.remainingAmount} type="number" value={paymentAmount} onChange={(e) => setPaymentAmount(e.target.value)} className="mt-5 h-11 w-full rounded-lg border border-[#C7A792] px-3" placeholder="Số tiền thu" /><input value={transactionCode} onChange={(e) => setTransactionCode(e.target.value)} className="mt-3 h-11 w-full rounded-lg border border-[#C7A792] px-3" placeholder="Mã giao dịch / chứng từ" /><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setPaymentDebt(null)}>Hủy</Button><Button className="bg-[#553B2F] text-white hover:bg-[#3f2a21]">Xác nhận thu</Button></div></form></div> : null}
  </AdminPageShell>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof FileCheck2; label: string; value: number }) { return <div className="rounded-xl border border-[#E8D3C7] bg-white p-5 shadow-sm"><Icon className="text-[#AA7864]" size={22} /><p className="mt-3 text-3xl font-black text-[#553B2F]">{value}</p><p className="mt-1 text-sm font-bold text-[#7a5547]">{label}</p></div>; }
