import { Router } from "express";
import { authRoutes } from "./Auth/Auth.routes.js";
import { categoryRoutes } from "./Category/Category.routes.js";
import { customerRoutes } from "./Customer/Customer.routes.js";
import { healthRoutes } from "./Health/Health.routes.js";
import { inventoryRoutes } from "./Inventory/Inventory.routes.js";
import { orderRoutes } from "./Order/Order.routes.js";
import { paymentRoutes } from "./Payment/Payment.routes.js";
import { paymentController } from "../controllers/Payment/Payment.controller.js";
import { asyncHandler } from "../middleware/asyncHandler.js";
import { productRoutes } from "./Product/Product.routes.js";
import { quoteRequestRoutes } from "./QuoteRequest/QuoteRequest.routes.js";
import { reportRoutes } from "./Report/Report.routes.js";
import promotionRoutes from "./Promotion/Promotion.routes.js";
import chatbotRoutes from './Chatbot/Chatbot.routes.js';
import { reviewRoutes } from "./Review/Review.routes.js";
import { uploadRoutes } from "./Upload/Upload.routes.js";
import { notificationRoutes } from "./Notification/Notification.routes.js";
import { b2bRoutes } from "./B2B/B2B.routes.js";

export const apiRoutes = Router();

apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/categories", categoryRoutes);
apiRoutes.use("/customers", customerRoutes);
apiRoutes.use("/health", healthRoutes);
apiRoutes.use("/inventories", inventoryRoutes);
apiRoutes.use("/orders", orderRoutes);
apiRoutes.use("/payments", paymentRoutes);
apiRoutes.post("/sepay/webhook", asyncHandler(paymentController.receiveSepayWebhook));
apiRoutes.use("/products", productRoutes);
apiRoutes.use("/quote-requests", quoteRequestRoutes);
apiRoutes.use("/reports", reportRoutes);
apiRoutes.use("/promotions", promotionRoutes);
apiRoutes.use("/chatbot", chatbotRoutes);
apiRoutes.use("/reviews", reviewRoutes);
apiRoutes.use("/uploads", uploadRoutes);
apiRoutes.use("/notifications", notificationRoutes);
apiRoutes.use("/b2b", b2bRoutes);
